#!/usr/bin/env python3
"""Build every blueprint folder: (re)generate, validate, render previews, refresh READMEs and the catalog.

    python3 tools/build.py                 # all blueprints: validate + previews + README auto sections + catalog
    python3 tools/build.py rail-buffer-station refined-concrete-60   # only these
    python3 tools/build.py --regen         # run each generate.py first (skips ones whose third_party input is missing)
    python3 tools/build.py --no-images     # skip PNG rendering (fast; CI uses this + git diff)
    python3 tools/build.py --renderer schematic   # simple coloured-box previews instead of game sprites

Images are rendered with real game sprites through Factorio Blueprint Editor (tools/render_fbe.py,
needs Playwright + Chromium: pip install -r tools/requirements.txt && python3 -m playwright install chromium).
If that is unavailable the schematic renderer (tools/render_preview.py) is used.

Per-blueprint layout (see blueprints/README.md):
    blueprints/<id>/meta.json        hand-written metadata (titles, summaries, outputs, variants, images…)
    blueprints/<id>/generate.py      optional generator that writes blueprint.txt (+ variants/*.txt)
    blueprints/<id>/blueprint.txt    the blueprint string
    blueprints/<id>/README.md        Korean doc; text between AUTO markers is rewritten by this tool
    blueprints/<id>/README.en.md     English doc, same rule
    blueprints/<id>/images/          preview.webp / detail.webp (generated) + attached screenshots
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[1]
BP_DIR = ROOT / "blueprints"
sys.path.insert(0, str(ROOT / "skills" / "factorio-blueprint" / "scripts"))
sys.path.insert(0, str(ROOT / "tools"))
from blueprint import decode, validate, _footprints, int_to_version  # noqa: E402
from render_preview import render, focus_box  # noqa: E402

SKIP_EXIT = 3
AUTO_START = "<!-- AUTO:START"
AUTO_END = "<!-- AUTO:END -->"
CAT_START = "<!-- CATALOG:START"
CAT_END = "<!-- CATALOG:END -->"

T = {
    "ko": {
        "auto_note": "tools/build.py가 생성하는 구역입니다. 직접 수정하지 마세요",
        "preview": "미리보기", "detail": "상세 (레일 제외 설비 부분)",
        "item": "항목", "value": "값", "game": "게임", "size": "크기", "tiles": "타일",
        "entities": "엔티티", "machines": "주요 설비", "inputs": "입력",
        "inputs_note": "블루프린트 안의 일정 신호 조합기 표시 (값 = 분당 필요량, 위치 = 블루프린트 왼쪽 위 기준 타일 좌표)",
        "signal": "신호", "thing": "아이템", "per_min": "분당", "where": "위치", "outputs": "출력", "files": "파일",
        "file": "파일", "desc": "설명", "default": "기본", "import": "가져오기",
        "import_how": "문자열을 클립보드에 복사한 뒤 게임에서 블루프린트 라이브러리 → 문자열 가져오기:",
        "regen": "다시 생성", "requires": "필요한 원본 (저장소에 포함되지 않음)", "gallery": "갤러리",
        "none": "없음", "validation": "검사", "ok": "통과",
        "roadmap": "로드맵", "stage": "단계", "research": "시기 / 필요한 연구", "todo": "할 일", "next": "다음에 지을 것",
        "render_note": "<sub>이미지: [Factorio Blueprint Editor](https://fbe.factorygamefan.com)로 렌더링 (게임 그래픽 © Wube Software)</sub>",
    },
    "en": {
        "auto_note": "generated by tools/build.py, do not edit",
        "preview": "Preview", "detail": "Detail (non-rail part)",
        "item": "Item", "value": "Value", "game": "Game", "size": "Size", "tiles": "tiles",
        "entities": "Entities", "machines": "Main machines", "inputs": "Inputs",
        "inputs_note": "constant-combinator markers inside the blueprint (count = required per minute, position = tile offset from the blueprint's top-left)",
        "signal": "Signal", "thing": "Item", "per_min": "Per minute", "where": "Position", "outputs": "Outputs", "files": "Files",
        "file": "File", "desc": "Description", "default": "default", "import": "Import",
        "import_how": "Copy the string to the clipboard, then in game: Blueprint library → Import string:",
        "regen": "Regenerate", "requires": "Required source files (not in the repo)", "gallery": "Gallery",
        "none": "none", "validation": "Validation", "ok": "OK",
        "roadmap": "Roadmap", "stage": "Stage", "research": "When / research needed", "todo": "What to do", "next": "Build next",
        "render_note": "<sub>Images rendered with [Factorio Blueprint Editor](https://fbe.factorygamefan.com) (game graphics © Wube Software)</sub>",
    },
}
MACHINE_TYPES = ("assembling-machine", "furnace", "mining-drill", "lab", "beacon", "rocket-silo",
                 "train-stop", "container", "logistic-container", "storage-tank")


TECH = json.loads((ROOT / "skills" / "factorio-blueprint" / "data" / "tech-unlocks.json").read_text())
PACK = {"automation-science-pack": ("빨강", "red"), "logistic-science-pack": ("초록", "green"),
        "military-science-pack": ("군사", "military"), "chemical-science-pack": ("파랑", "blue"),
        "production-science-pack": ("보라", "purple"), "utility-science-pack": ("노랑", "yellow"),
        "space-science-pack": ("우주", "space"), "metallurgic-science-pack": ("불카누스", "Vulcanus"),
        "electromagnetic-science-pack": ("풀가오라", "Fulgora"), "agricultural-science-pack": ("글레바", "Gleba"),
        "cryogenic-science-pack": ("아킬로", "Aquilo"), "promethium-science-pack": ("프로메튬", "promethium")}


TRIGGER = {"craft-item": ("아이템을 처음 만들면", "on first craft"), "mine-entity": ("처음 캐면", "on first mining"),
           "build-entity": ("처음 지으면", "on first build"), "create-space-platform": ("첫 우주 플랫폼을 만들면", "on the first space platform"),
           "send-item-to-orbit": ("궤도로 보내면", "on sending to orbit"), "craft-fluid": ("유체를 처음 만들면", "on first fluid craft"),
           "capture-spawner": ("둥지를 잡으면", "on capturing a spawner")}


def stack_section(name, lang):
    """Stacking table for a stackable cell (lib/cells.py), from the same analysis that built it."""
    sys.path.insert(0, str(ROOT))
    from lib.cells import CELLS
    from lib.stack import TIERS as STIERS, analyse
    cell = CELLS[name]
    ko = lang == "ko"
    out = ["", "### " + ("쌓기" if ko else "Stacking"), "",
           (f"셀 하나 = **{cell.width}×{cell.period}** (가로×세로). 같은 셀을 바로 북쪽({cell.period}칸 위)에 붙이면 "
            f"벨트가 그대로 이어집니다. 셀 파일은 {cell.width}×{cell.period} 격자에 맞춰 붙으니 드래그로 여러 개를 놓으세요. "
            "캡(시작 조각)은 맨 아래 한 번만 놓습니다." if ko else
            f"One cell = **{cell.width}×{cell.period}** (width×height). A copy pasted directly north ({cell.period} rows up) "
            f"continues every belt; the cell files snap to a {cell.width}×{cell.period} grid, so drag to place several. "
            "The cap (base piece) goes once at the bottom."), "",
           ("| 단계 | 셀당 출력 (분당) | 최대 셀 수 | 셀당 입력, 한쪽 (분당) | 비고 |" if ko else
            "| Stage | Output per cell (/min) | Max cells | Input per cell, one side (/min) | Notes |"),
           "|---|---:|---:|---|---|"]
    for tier, t in STIERS.items():
        a = analyse(cell, tier)
        inputs = ", ".join(f"{icon(i)} {v * 60:.0f}" for i, v in sorted(a["lane_per_side"].items()))
        note = ""
        if a["limited"]:
            note = ("인서터 제한: " if ko else "inserter-limited: ") + ", ".join(
                f"{r} {u * 100:.0f}%" for r, u in a["limited"].items())
        out.append(f"| {t['label'][lang]} | {a['out_per_s'] * 60:.1f} | {a['max_cells']} | {inputs} | {note} |")
    out += ["", ("_최대 셀 수 = 그 단계 벨트의 레인 하나로 버틸 수 있는 셀 수(가장 바쁜 입력 레인이나 출력 레인 기준). "
                 "양쪽이 따로 입력을 받으므로 버스 분기는 한쪽마다 하나씩 필요합니다._" if ko else
                 "_Max cells = how many cells one lane of that tier's belt can feed (busiest input lane or the product "
                 "lane). Each side has its own inputs, so every input needs one bus tap per side._")]
    return out


def family_section(name, lang):
    """Cell types of a mall-style family (lib/cells.py list `name`)."""
    sys.path.insert(0, str(ROOT))
    import lib.cells as C
    from lib.stack import RECIPES
    cells = getattr(C, name)
    ko = lang == "ko"
    out_item = lambda r: RECIPES[r]["results"][0]["name"]
    first = cells[0]
    out = ["", "### " + ("셀 종류" if ko else "Cell types"), "",
           (f"모든 셀의 폭은 **{first.width}**칸이고 같은 레인을 씁니다. 맨 아래 셀이 공용 레인을 채우는 중간재(예: 톱니)를 "
            "만들므로 그 셀을 캡 바로 위에 놓고, 나머지 셀은 필요한 것만 원하는 순서로 북쪽에 붙입니다. "
            "제품은 가운데 상자(2칸 제한)에 쌓입니다." if ko else
            f"Every cell is **{first.width}** wide and uses the same lanes. The bottom cell makes the shared intermediates "
            "(e.g. gears) for the lanes, so it goes right above the cap; add any other cells northwards in any order. "
            "Products collect in the centre chests (limited to 2 slots)."), "",
           ("| 셀 | 크기 | 서쪽 (남→북) | 동쪽 (남→북) |" if ko else "| Cell | Size | West (south→north) | East (south→north) |"),
           "|---|---|---|---|"]
    for cell in cells:
        w = " → ".join(icon(out_item(r)) for r in cell.column)
        e = " → ".join(icon(out_item(r)) for r in (cell.east or cell.column))
        out.append(f"| {cell.name.split(':')[-1].strip()} | {cell.width}×{cell.period} | {w} | {e} |")
    lanes = first.lanes()
    out += ["", ("레인: " if ko else "Lanes: ") + ", ".join(
        f"{icon(i)} ({'안쪽' if ko and v[0] == 'inner' else '바깥' if ko else v[0]}"
        + (", 셀 안에서 만듦" if ko and i in first.makers() else ", made in the cell" if i in first.makers() else "") + ")"
        for i, v in lanes.items())]
    return out


def planet_section(name, lang):
    """Stacks, bus and power of a planet complex (lib/planets/<name>.py), from the same code that built it."""
    import importlib
    sys.path.insert(0, str(ROOT))
    mod = importlib.import_module(f"lib.planets.{name}")
    from lib.fstack import analyse as fan
    from lib.complex import compose
    ko = lang == "ko"
    out = ["", "### " + ("단지 구성" if ko else "Complex"), "",
           ("| 줄 | 셀 크기 | 셀 수 | 출력 (분당, 후반) | 입력 (분당, 후반) |" if ko else
            "| Line | Cell | Cells | Output (/min, late) | Inputs (/min, late) |"), "|---|---|---:|---|---|"]
    for key, n in mod.PLAN:
        c = mod.C[key]
        a = fan(c, "late")
        outs = ", ".join(f"{icon(k, 'fluid' if k in c.fluids_out else 'item')} {v * 60 * n:,.0f}" for k, v in a["out_per_s"].items())
        ins = ", ".join(f"{icon(k, 'fluid' if k in c.fluids_in else 'item')} {2 * v * 60 * n:,.0f}" for k, v in a["in_per_side"].items())
        if c.centre == "chest":
            outs = ("상자 (몰)" if ko else "chests (mall)")
        out.append(f"| {c.name} | {c.width}×{c.period} | {n} | {outs} | {ins} |")
    bp, rep = compose(name, mod.LAYOUT, mod.stacks(), tier=mod.BUS_TIER)
    bp.connect_poles()
    use, gen = mod.power_budget(bp)
    out += ["", ("버스 (위 → 아래, 6줄 + 빈 2줄 묶음; 유체는 맨 아래):" if ko else "Bus (top → bottom, 6 lanes + 2 empty rows per group; fluids at the bottom):"), "",
            ("| 묶음 | 줄 |" if ko else "| Group | Lanes |"), "|---|---|"]
    for g, grp in enumerate(mod.LAYOUT):
        out.append(f"| {g + 1} ({grp['kind']}) | " + ", ".join(icon(i, 'fluid' if grp['kind'] == 'fluid' else 'item') if i else "-" for i in grp["lanes"]) + " |")
    out += ["", (f"전체 {len(bp.entities):,}개 엔티티, 폭 {rep['x_end']}칸. 최대 전력 {use / 1000:,.0f} MW / 발전 {gen / 1000:,.0f} MW. "
                 "버스 줄마다 수요가 한 줄 용량(파랑 벨트 45/s, 파이프 1,200/s)을 넘지 않는지 생성할 때 검사합니다." if ko else
                 f"{len(bp.entities):,} entities, {rep['x_end']} tiles wide. Peak power {use / 1000:,.0f} MW / generated {gen / 1000:,.0f} MW. "
                 "Every bus lane is checked at generation time against one lane's capacity (blue belt 45/s, pipe 1,200/s).")]
    return out


def trigger_text(trig, lang):
    if not trig:
        return "-"
    kind, _, what = trig.partition(":")
    base = TRIGGER.get(kind, (kind, kind))[0 if lang == "ko" else 1]
    return base + (f" `{what}`" if what else "")


def research_text(recipes, lang):
    """Recipe names -> 'tech (packs)' using the unlock data, so roadmaps never name a wrong technology."""
    i = 0 if lang == "ko" else 1
    seen, parts = set(), []
    for r in recipes:
        techs = TECH["recipe_unlocked_by"].get(r)
        if not techs:
            raise SystemExit(f"roadmap: no technology unlocks recipe {r!r}")
        t = techs[0]
        if t in seen:
            continue
        seen.add(t)
        e = TECH["technologies"][t]
        packs = [PACK[x][i] for x in PACK if x in e["packs"]]
        trig = e.get("space_age", {}).get("trigger") or e.get("trigger")
        how = "·".join(packs) if packs else trigger_text(trig, lang)
        parts.append(f"`{t}` ({how})")
    return ", ".join(parts)


def load_meta(d: pathlib.Path) -> dict:
    return json.loads((d / "meta.json").read_text())


def blueprint_files(d: pathlib.Path, meta: dict):
    yield "blueprint.txt", meta.get("default_label", {"ko": T["ko"]["default"], "en": T["en"]["default"]})
    for v in meta.get("variants", []):
        yield v["file"], v["label"]


def variant_image(v: dict) -> str:
    """images/<variant file stem>.webp for variants with "preview": true in meta.json."""
    return "images/" + pathlib.Path(v["file"]).stem + ".webp"


def stats(obj: dict) -> dict:
    bp = obj["blueprint"]
    fps = list(_footprints(bp))
    minx = min(f[2] for f in fps); miny = min(f[3] for f in fps)
    maxx = max(f[2] + f[4] for f in fps); maxy = max(f[3] + f[5] for f in fps)
    from blueprint import type_of
    machines = Counter()
    for e in bp["entities"]:
        if type_of(e["name"]) in MACHINE_TYPES:
            machines[(e["name"], e.get("recipe"))] += 1
    markers = []
    for e in bp["entities"]:
        if e["name"] != "constant-combinator":
            continue
        secs = e.get("control_behavior", {}).get("sections", {}).get("sections", [])
        filters = [f for s in secs for f in s.get("filters", [])]
        if len(filters) == 1 and filters[0].get("count", 0) > 0 and not e.get("player_description"):
            f = filters[0]
            markers.append({"signal": f["name"], "type": f.get("type", "item"), "count": f["count"],
                            "x": int(e["position"]["x"] - minx), "y": int(e["position"]["y"] - miny)})
    return {"w": maxx - minx, "h": maxy - miny, "entities": len(bp["entities"]),
            "machines": machines, "markers": markers, "version": int_to_version(bp.get("version", 0)),
            "problems": validate(obj)}


def icon(name: str, typ: str = "item") -> str:
    return f"`{name}`" + (" (fluid)" if typ == "fluid" else "")


def machines_text(m: Counter) -> str:
    if not m:
        return "-"
    by_name = Counter()
    recipes = {}
    for (name, recipe), c in m.items():
        by_name[name] += c
        if recipe:
            recipes.setdefault(name, Counter())[recipe] += c
    parts = []
    for name, c in by_name.most_common():
        r = recipes.get(name)
        detail = f" ({', '.join(f'{k} {v}' for k, v in r.most_common())})" if r else ""
        parts.append(f"`{name}` ×{c}{detail}")
    return "<br>".join(parts)


def auto_section(d: pathlib.Path, meta: dict, st: dict, lang: str) -> str:
    t = T[lang]
    bid = d.name
    out = [f"{AUTO_START} ({t['auto_note']}) -->", ""]
    if (d / "images" / "preview.webp").exists():
        if any(v.get("preview") for v in meta.get("variants", [])) and meta.get("default_label"):
            out += [f"**{meta['default_label'][lang]}**", ""]
        out.append(f"![{t['preview']}](images/preview.webp)")
    if (d / "images" / "detail.webp").exists():
        out += ["", f"**{t['detail']}**", "", f"![{t['detail']}](images/detail.webp)"]
    for v in meta.get("variants", []):
        if v.get("preview") and (d / variant_image(v)).exists():
            out += ["", f"**{v['label'][lang]}**", "", f"![{v['label'][lang]}]({variant_image(v)})"]
    if (d / "images" / "preview.webp").exists():
        out += ["", t["render_note"]]
    mods = ", ".join(meta.get("mods", ["base"]))
    out += ["", f"| {t['item']} | {t['value']} |", "|---|---|",
            f"| {t['game']} | Factorio {meta.get('game', '2.0')} ({mods}) |",
            f"| {t['size']} | {st['w']}×{st['h']} {t['tiles']} |",
            f"| {t['entities']} | {st['entities']} |",
            f"| {t['machines']} | {machines_text(st['machines'])} |",
            f"| {t['validation']} | {t['ok'] if not st['problems'] else '; '.join(st['problems'])} |", ""]
    out += [f"### {t['inputs']}", ""]
    if st["markers"]:
        out += [f"_{t['inputs_note']}_", "", f"| {t['signal']} | {t['per_min']} | {t['where']} |", "|---|---:|---|"]
        out += [f"| {icon(m['signal'], m['type'])} | {m['count']:,} | ({m['x']}, {m['y']}) |" for m in st["markers"]]
    elif meta.get("inputs"):
        out += [f"| {t['thing']} | {t['per_min']} | {t['where']} |", "|---|---:|---|"]
        out += [f"| {icon(i['item'])} | {i.get('per_minute', '-')} | {i.get('where', {}).get(lang, '')} |" for i in meta["inputs"]]
    else:
        out.append(t["none"])
    out += ["", f"### {t['outputs']}", ""]
    if meta.get("outputs"):
        out += [f"| {t['thing']} | {t['per_min']} | {t['where']} |", "|---|---:|---|"]
        out += [f"| {icon(o['item'])} | {o.get('per_minute', '-')} | {o.get('where', {}).get(lang, '')} |" for o in meta["outputs"]]
    else:
        out.append(t["none"])
    if meta.get("cell"):
        out += stack_section(meta["cell"], lang)
    if meta.get("family"):
        out += family_section(meta["family"], lang)
    if meta.get("planet"):
        out += planet_section(meta["planet"], lang)
    if meta.get("roadmap"):
        out += ["", f"### {t['roadmap']}", "", f"| {t['stage']} | {t['research']} | {t['todo']} |", "|---|---|---|"]
        for st_ in meta["roadmap"]:
            res = research_text(st_.get("research", []), lang) or "-"
            if st_.get("when"):
                res = st_["when"][lang] + ("<br>" + res if res != "-" else "")
            out.append(f"| {st_['stage'][lang]} | {res} | {st_['do'][lang]} |")
    if meta.get("next"):
        out += ["", f"**{t['next']}**", ""]
        for n in meta["next"]:
            nd = BP_DIR / n["id"]
            title = load_meta(nd)["title"][lang] if (nd / "meta.json").exists() else n["id"]
            readme = "README.md" if lang == "ko" else "README.en.md"
            out.append(f"- [{title}](../{n['id']}/{readme}) — {n['why'][lang]}")
    out += ["", f"### {t['files']}", "", f"| {t['file']} | {t['desc']} |", "|---|---|"]
    for f, label in blueprint_files(d, meta):
        out.append(f"| [`{f}`]({f}) | {label[lang]} |")
    out += ["", f"{t['import_how']}", "", "```sh", f"pbcopy < blueprints/{bid}/blueprint.txt   # macOS",
            f"xclip -selection clipboard < blueprints/{bid}/blueprint.txt   # Linux", "```"]
    if (d / "generate.py").exists():
        out += ["", f"### {t['regen']}", "", "```sh", f"python3 blueprints/{bid}/generate.py", "python3 tools/build.py " + bid, "```"]
        if meta.get("requires"):
            out += ["", f"{t['requires']}: " + ", ".join(f"`third_party/{r}`" for r in meta["requires"])]
    imgs = meta.get("images", [])
    if imgs:
        out += ["", f"### {t['gallery']}", ""]
        for im in imgs:
            out += [f"![{im['caption'][lang]}]({im['file']})", "", f"_{im['caption'][lang]}_", ""]
    out += ["", AUTO_END]
    return "\n".join(out)


def readme_template(meta: dict, lang: str) -> str:
    other = "README.en.md" if lang == "ko" else "README.md"
    other_label = "English" if lang == "ko" else "한국어"
    return (f"# {meta['title'][lang]}\n\n> {meta['summary'][lang]}\n\n[{other_label}]({other})\n\n"
            f"{AUTO_START} -->\n{AUTO_END}\n")


def update_readme(d: pathlib.Path, meta: dict, st: dict, lang: str):
    name = "README.md" if lang == "ko" else "README.en.md"
    p = d / name
    text = p.read_text() if p.exists() else readme_template(meta, lang)
    section = auto_section(d, meta, st, lang)
    if AUTO_START in text and AUTO_END in text:
        new = re.sub(re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END), lambda _: section, text, flags=re.S)
    else:
        new = text.rstrip() + "\n\n" + section + "\n"
    if new != text:
        p.write_text(new)
        print(f"  updated {p.relative_to(ROOT)}")


def catalog(entries, lang: str) -> str:
    t = T[lang]
    head = {"ko": "| 미리보기 | 블루프린트 | 설명 | 크기 | 입력 |", "en": "| Preview | Blueprint | Summary | Size | Inputs |"}[lang]
    rows = [f"{CAT_START} ({t['auto_note']}) -->", "", head, "|---|---|---|---|---|"]
    for d, meta, st in entries:
        readme = "README.md" if lang == "ko" else "README.en.md"
        img = f'<img src="blueprints/{d.name}/images/preview.webp" width="160">' if (d / "images" / "preview.webp").exists() else ""
        inputs = (", ".join(f"{m['signal']} {m['count']:,}/min" for m in st["markers"])
                  or ", ".join(f"{i['item']} {i.get('per_minute', '')}/min" for i in meta.get("inputs", []))
                  or "-")
        tags = " ".join(f"`{x}`" for x in meta.get("tags", []))
        rows.append(f"| {img} | [{meta['title'][lang]}](blueprints/{d.name}/{readme})<br>{tags} | "
                    f"{meta['summary'][lang]} | {st['w']}×{st['h']} | {inputs} |")
    rows += ["", CAT_END]
    return "\n".join(rows)


def update_catalog(entries):
    for lang, name in (("ko", "README.md"), ("en", "README.en.md")):
        p = ROOT / name
        if not p.exists():
            continue
        text = p.read_text()
        section = catalog(entries, lang)
        if CAT_START in text:
            new = re.sub(re.escape(CAT_START) + r".*?" + re.escape(CAT_END), lambda _: section, text, flags=re.S)
            if new != text:
                p.write_text(new)
                print(f"updated {name} catalog")


def save_webp(img, path):
    """Generated previews are WebP (q85): 3-5x smaller than PNG for sprite renders."""
    img.convert("RGB").save(path, format="WEBP", quality=85, method=6)
    for old in (path.with_suffix(".png"),):          # drop the PNG of an older build
        if old.exists():
            old.unlink()


class Images:
    """Preview renderer: 'fbe' (game sprites, shared browser) with fallback to 'schematic'."""

    def __init__(self, kind: str):
        self.kind, self.fbe = kind, None
        if kind == "fbe":
            try:
                from render_fbe import FBERenderer
                self.fbe = FBERenderer()
            except Exception as e:          # playwright missing, no network, …
                print(f"! FBE renderer unavailable ({type(e).__name__}: {str(e)[:120]}); using schematic previews")
                self.kind = "schematic"

    def render(self, obj: dict, title: str, box=None):
        if self.kind == "fbe":
            from render_fbe import finish, sub_blueprint
            from blueprint import encode
            src = sub_blueprint(obj, box) if box else obj
            return finish(self.fbe.render(encode(src)))
        return render(obj, title=title, box=box)

    def close(self):
        if self.fbe:
            self.fbe.close()


def build_one(d: pathlib.Path, regen: bool, images):
    meta = load_meta(d)
    print(f"[{d.name}]")
    if regen and (d / "generate.py").exists():
        r = subprocess.run([sys.executable, str(d / "generate.py")], cwd=ROOT, capture_output=True, text=True)
        if r.returncode == SKIP_EXIT:
            print("  generate: skipped (" + r.stderr.strip().splitlines()[-1] + ")")
        elif r.returncode != 0:
            raise SystemExit(f"  generate.py failed:\n{r.stdout}\n{r.stderr}")
        else:
            print("  generate: ok")
    problems = []
    st = None
    for f, _ in blueprint_files(d, meta):
        obj = decode((d / f).read_text())
        s = stats(obj)
        if s["problems"] and not meta.get("allow_problems"):
            problems += [f"{f}: {p}" for p in s["problems"]]
        if f == "blueprint.txt":
            st = s
            if images:
                img_dir = d / "images"; img_dir.mkdir(exist_ok=True)
                title = meta["title"]["en"]
                save_webp(images.render(obj, title), img_dir / "preview.webp")
                box = focus_box(obj)
                total = s["w"] * s["h"]
                if box and (box[2] - box[0]) * (box[3] - box[1]) < 0.5 * total:
                    save_webp(images.render(obj, title + " (detail)", box), img_dir / "detail.webp")
                print(f"  images: {images.kind}")
    if images:
        for v in meta.get("variants", []):
            if v.get("preview"):
                obj = decode((d / v["file"]).read_text())
                save_webp(images.render(obj, f"{meta['title']['en']} - {v['label']['en']}"), d / variant_image(v))
    if problems:
        raise SystemExit("  validation failed:\n    " + "\n    ".join(problems))
    for lang in ("ko", "en"):
        update_readme(d, meta, st, lang)
    return d, meta, st


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("ids", nargs="*")
    ap.add_argument("--regen", action="store_true")
    ap.add_argument("--no-images", action="store_true")
    ap.add_argument("--renderer", choices=("fbe", "schematic"), default="fbe")
    a = ap.parse_args()
    images = None if a.no_images else Images(a.renderer)
    dirs = sorted(p for p in BP_DIR.iterdir() if (p / "meta.json").exists())
    entries = []
    for d in dirs:
        if a.ids and d.name not in a.ids:
            meta = load_meta(d)
            entries.append((d, meta, stats(decode((d / "blueprint.txt").read_text()))))
            continue
        entries.append(build_one(d, a.regen, images))
    if images:
        images.close()
    entries.sort(key=lambda e: (e[1].get("order", 100), e[0].name))
    update_catalog(entries)


if __name__ == "__main__":
    main()
