#!/usr/bin/env python3
"""Render images + raw analysis for docs/demo-analysis from the git-ignored demo-resources/ folder.

    .venv/bin/python tools/render_demo.py [slug ...]
Writes docs/demo-analysis/images/<slug>.webp (single) or <slug>-sheet.webp (book) and
docs/demo-analysis/data/<slug>.md (tools/analyze_blueprint.py output)."""
import json, pathlib, subprocess, sys, unicodedata

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "demo-analysis"
SRC = ROOT / "demo-resources"
PY = sys.executable


def find(name):
    want = unicodedata.normalize("NFC", name)
    for p in SRC.iterdir():
        if unicodedata.normalize("NFC", p.name) == want:
            return p
    raise FileNotFoundError(name)


def main():
    sources = json.loads((DOC / "sources.json").read_text())
    (DOC / "data").mkdir(exist_ok=True)
    for slug, s in sources.items():
        if len(sys.argv) > 1 and slug not in sys.argv[1:]:
            continue
        f = find(s["file"])
        rep = subprocess.run([PY, str(ROOT / "tools" / "analyze_blueprint.py"), str(f)], capture_output=True, text=True, check=True).stdout
        (DOC / "data" / f"{slug}.md").write_text(f"<!-- generated by tools/render_demo.py from demo-resources/{s['file']} -->\n\n{rep}")
        if s["kind"] == "single":
            cmd = [PY, str(ROOT / "tools" / "render_fbe.py"), str(f), "-o", str(DOC / "images" / f"{slug}.webp")]
        else:
            cmd = [PY, str(ROOT / "tools" / "contact_sheet.py"), str(f), "-o", str(DOC / "images" / f"{slug}-sheet.webp"),
                   "--cols", "5", "--cell", "300"]
        print(f"== {slug}", flush=True)
        subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
